### ISSUE TITLE
Allow CRUD operations on uploaded course material files

### ISSUE THREAD

**Issue by SandeepMango159** [afstudeerprojecten/FeedbackAI-Tool#11]
Allow the teacher to perform CRUD (create, read, update, delete) operations on their uploaded files for their courses.

#### Tasks
- [ ] ability to read and consult course material files as a teacher
- [ ] ability to download your uploaded course material files again
- [ ] ability to edit your uploaded course material files
- [ ] ability to delete your course material files
